codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project:
      default:
        target: 90%
        threshold: 5%
  ignore:
    - "src/algokit/cli/**"
    - "src/algokit/viz/**"
    - "src/algokit/core/**"
    - "tests/**"
    - "docs/**"
    - "examples/**"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
