"""Main macro functions for AlgoKit documentation.

These functions are automatically loaded by MkDocs Macros.
"""

from datetime import datetime


def test_macro():
    """Return a simple test message to verify macros are working."""
    return "🎉 **MkDocs Macros is working!** This message was generated by a Python function."


def get_current_date():
    """Return the current date in a formatted string."""
    return datetime.now().strftime("%B %d, %Y")


def get_project_info():
    """Return basic project information."""
    return {
        "name": "AlgoKit",
        "description": "A python implementation of control and learning algorithms",
        "status": "Active Development",
        "macros_enabled": True,
    }


def get_algorithm_families():
    """Return list of algorithm families for navigation."""
    return [
        "Dynamic Programming",
        "Reinforcement Learning",
        "Control",
        "MPC",
        "Hierarchical RL",
        "Planning",
        "Gaussian Process",
        "DMPs",
        "Real-Time Control",
    ]
