name: Commitizen bump

on:
  push:
    branches: [main]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Commitizen Bump
        uses: commitizen-tools/commitizen-action@v0.24.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
