name: Documentation

on:
  # Build + publish rendered docs whenever main changes
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "pyproject.toml"
      - "src/**"

  # Allow manual rebuilds
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # ─── 1️⃣ Checkout ----------------------------------------------------------------
      - uses: actions/checkout@v5

      # ─── 2️⃣ Install the same interpreter you test with ------------------------------
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "uv"

      # ─── 3️⃣ Install uv + nox (same bootstrap used in ci_nox.yml) --------------------
      - run: |
          python -m pip install --quiet uv
          uv pip install --system --quiet 'nox>=2024.4.15'

      # ─── 4️⃣ Build docs via the existing nox session ---------------------------------
      - name: Build MkDocs HTML
        run: nox --sessions docs            # builds into site/

      # ─── 4️⃣ Documentation built successfully --------------------------------------
      # Note: Documentation deployment is handled by the dedicated deploy-docs.yml workflow
